import Head from 'next/head'
import BlogCard from '../components/BlogCard'

export default function Home({postsData}) {
 
  return (
    <div >
      <Head>
        <title>NextBlog | Home</title>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
        
      rel="stylesheet"></link>
      </Head>

      <style>
@import url(&apos;https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap&apos;);
</style>
<style>
@import url(&apos;https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,400;0,500;0,900;1,700&display=swap&apos;);
</style>


<div id="heroin" className=" hero min-h-screen" >
  <div className="hero-overlay bg-opacity-60"></div>
  <div className="hero-content text-center text-neutral-content">
    <div className="max-w-md">
      <h1 className="mb-5 text-5xl font-bold">Hello there</h1>
      <p className="mb-5">Provident cupiditate voluptatem et in. Quaerat fugiat ut assumenda excepturi exercitationem quasi. In deleniti eaque aut repudiandae et a id nisi.</p>
      <button className="btn btn-primary">Get Started</button>
    </div>
  </div>
</div>
      

      {/* {session ? <button onClick={signOut}>Log out</button> : <button onClick={signIn}> Log in  </button>} */}

      <div className='card'>
        <div className="card-body">
          <div className='card-title'>Latest Post </div>
        </div>
      </div>



      

{      console.log(postsData)}
    


<div className={"flex justify-center  flex-wrap"}>
      {postsData.map((post) => (

          <BlogCard
          key={post.id}
          id={post.id}
          title={post.title}
          // subTitle={post.body}
          subTitle={post.content}
          description={post.author.email}>
        </BlogCard>
          )
          )
        }

        </div>
      {/* <BlogCard
        title="post Blog Post 1"
        subTitle={`First Blog Card`}
        description={`This is a blog post made to show how to create a site.`}>
      </BlogCard> */}

      {/* <BlogCard
        title="Blog Post 2"
        subTitle={`Second Blog Card `}
        description={`This is a blog post made to show how to create a site.`}>
      </BlogCard>

      <BlogCard
        title="Blog Post 3"
        subTitle={`Third Blog Card`}
        description={`This is a blog post made to show how to create a site.`}>
      </BlogCard>

      <BlogCard
        title="Blog Post 4"
        subTitle={`Fourth Blog Card`}
        description={`This is a blog post made to show how to create a site.`}>
      </BlogCard>

      <BlogCard
        title="Blog Post 5"
        subTitle={`Fifth Blog Card`}
        description={`This is a blog post made to show how to create a site.`}>
      </BlogCard>

      <BlogCard
        title="Blog Post 6"
        subTitle={`Sixth Blog Card`}
        description={`This is a blog to post made to show how to create a site.`}>
      </BlogCard> */}
    </div>
  )
}

export const getServerSideProps= async() =>{

  const response = await fetch('https://nextjs-blog-tau-seven-60.vercel.app/api/postapi');
  const postsData = await response.json();


  return{props: {
     postsData
  }}
}

