import Head from 'next/head'
import BlogCard from '../components/BlogCard'

export default function Home({postsData}) {
 
  return (
    <div >
      <Head>
        <title>NextBlog | Home</title>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet"></link>
      </Head>

      <h2 className={`px-4 font-bold dark:text-2xl dark:bg-black dark:text-white`}>Published Posts</h2>
      <p></p>

      {/* {session ? <button onClick={signOut}>Log out</button> : <button onClick={signIn}> Log in  </button>} */}
      
      {postsData.map((post) => (

        <BlogCard
          key={post.id}
          title={post.title}
          // subTitle={post.body}
          subTitle={post.author.name}
          description={post.author.email}>
        </BlogCard>
          )
        )
      }

      {/* <BlogCard
        title="post Blog Post 1"
        subTitle={`First Blog Card`}
        description={`This is a blog post made to show how to create a site.`}>
      </BlogCard> */}

      {/* <BlogCard
        title="Blog Post 2"
        subTitle={`Second Blog Card `}
        description={`This is a blog post made to show how to create a site.`}>
      </BlogCard>

      <BlogCard
        title="Blog Post 3"
        subTitle={`Third Blog Card`}
        description={`This is a blog post made to show how to create a site.`}>
      </BlogCard>

      <BlogCard
        title="Blog Post 4"
        subTitle={`Fourth Blog Card`}
        description={`This is a blog post made to show how to create a site.`}>
      </BlogCard>

      <BlogCard
        title="Blog Post 5"
        subTitle={`Fifth Blog Card`}
        description={`This is a blog post made to show how to create a site.`}>
      </BlogCard>

      <BlogCard
        title="Blog Post 6"
        subTitle={`Sixth Blog Card`}
        description={`This is a blog to post made to show how to create a site.`}>
      </BlogCard> */}
    </div>
  )
}

export const getServerSideProps= async() =>{

  const response = await fetch('http://localhost:3000/api/postapi');
  const postsData = await response.json();

  return{props: {
     postsData
  }}
}

