import Head from 'next/head'
import BlogCard from '../components/BlogCard'
import {useState} from 'react'
// import { signIn } from "next-auth/react"
import { useSession, status, signIn, signOut} from "next-auth/react"




// const posts = JSON.stringify(raw);


export default function Home({postsData}) {

  const { data: session, status } = useSession();
    console.log("session id: ", session);

    if(status === "loading"){
        return " ";
    }

   
 
  // const posts =[
  //   {id: 1, title: "title1", subTitle: "subTitle1", description: "description1" },
  //   {id: 2, title: "title2", subTitle: "subTitle2", description: "description2" },
  //   {id: 3, title: "title3", subTitle: "subTitle3", description: "description3" },
  
  
  // ];

  const posts = [];
  return (
    <div >
      <Head>
        <title>NextBlog | Home</title>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet"></link>
      </Head>

      <h2 className={`px-4 font-bold dark:text-2xl dark:bg-black dark:text-white`}>Published Posts</h2>
      <p></p>

      {/* {session ? <button onClick={signOut}>Log out</button> : <button onClick={signIn}> Log in  </button>} */}
      
      {postsData.map((post) => (

        <BlogCard
          key={post.id}
          title={post.title}
          // subTitle={post.body}
          subTitle={post.author.name}
          description={post.author.email}>
        </BlogCard>
          )
        )
      }

      <BlogCard
        title="Blog Post 1"
        subTitle={`First Blog Card`}
        description={`This is a blog post made to show how to create a site.`}>
      </BlogCard>

      <BlogCard
        title="Blog Post 2"
        subTitle={`Second Blog Card `}
        description={`This is a blog post made to show how to create a site.`}>
      </BlogCard>

      <BlogCard
        title="Blog Post 3"
        subTitle={`Third Blog Card`}
        description={`This is a blog post made to show how to create a site.`}>
      </BlogCard>

      <BlogCard
        title="Blog Post 4"
        subTitle={`Fourth Blog Card`}
        description={`This is a blog post made to show how to create a site.`}>
      </BlogCard>

      <BlogCard
        title="Blog Post 5"
        subTitle={`Fifth Blog Card`}
        description={`This is a blog post made to show how to create a site.`}>
      </BlogCard>

      <BlogCard
        title="Blog Post 6"
        subTitle={`Sixth Blog Card`}
        description={`This is a blog to post made to show how to create a site.`}>
      </BlogCard>
    </div>
  )
}

export const getServerSideProps= async() =>{

  const response = await fetch('https://nextjs-blog-tau-seven-60.vercel.app/api/postapi');
  // const response = await fetch('https://jsonplaceholder.typicode.com/posts?_limit=6')
  const postsData = await response.json();

  return{props: {
    postsData
  }}
}

