import React from 'react'
import Head from 'next/head'
import BlogCard from '../components/BlogCard'
import { useSession} from "next-auth/react"
import useSWR from 'swr'
import Link from 'next/link'



function Posts () {
  const { data: session, status } = useSession();

  const response  =(url) => fetch(url, {
    method: 'POST', 
    headers: {'Content-Type': 'application/json',},
    body: JSON.stringify(session),
  })
  .then((responses) => responses.json());

  const { data, error } = useSWR("api/postapi", response);

  if(status === "loading"){
    console.log(data);
      return " ";
  }

  if(status=== "unauthenticated"){
    return <p>Access Denied</p>
  }

    if (error) return "An error has occurred.";
    if (!data) return " ";
    
    return (
      <div>
        <Head>
          <title>Post | NextBlog</title>
          <meta charset="UTF-8" />
          <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <h1>Posts</h1>
        <Link href='/post/create'>
        <a >Create New Post
          </a></Link>
        
        
        {data.map((post) => (

          <BlogCard
          key={post.id}
          title={post.title}
          subTitle={post.author.email}
          description={JSON.stringify(post.author.role)}>
          </BlogCard>
            )
          )
        }
        
      </div>
    )
}
export default Posts