import React from 'react'
import Head from 'next/head'
import BlogCard from '../components/BlogCard'


const posts = ({postsData}) => {

  
  return (
    <div>
      <Head>
        <title>Post | NextBlog</title>
        <meta charset="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Posts</h1>
      
      {postsData.map((post) => (

        <BlogCard
        key={post.id}
        title={post.title}
        subTitle={post.author.email}
        description={JSON.stringify(post.author.role)}>
        </BlogCard>
  )
)
}
    </div>
  )
}


export const getServerSideProps= async() =>{

    const response = await fetch('https://nextjs-blog-tau-seven-60.vercel.app/api/postapi');
    
    // const response = await fetch('https://jsonplaceholder.typicode.com/posts?_limit=6')
    const postsData = await response.json();
  
    return{props: {
      postsData
    }}
  }

export default posts